name: Build and Test Ubuntu with dbus

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: |
          docker build -t my-ubuntu-dbus:latest .
          docker images  # List images to verify the build

      - name: Test if dbus-daemon is running
        run: |
          docker exec dbus-test pgrep dbus-daemon || { echo "dbus-daemon not running"; exit 1; }

      - name: Test if the dbus system is responding
        run: |
          docker exec dbus-test dbus-send --system --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.ListNames

      - name: Test if a specific dbus service is available (example: org.freedesktop.login1)
        run: |
          docker exec dbus-test dbus-send --system --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.GetNameOwner string:org.freedesktop.login1 || { echo "org.freedesktop.login1 service not found"; exit 1; }

      - name: Test the status of dbus
        run: |
          docker exec dbus-test dbus-send --system --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.Peer.Ping || { echo "dbus is not responding to ping"; exit 1; }


      - name: Cleanup
        run: docker rm -f dbus-test


  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run the dbus check
        run: |
          docker run --rm my-ubuntu-dbus:latest dbus-send --system --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.ListNames
