name: Build and Test Ubuntu with dbus

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: |
          docker build -t my-ubuntu-dbus:latest .
          docker images  # List images to verify the build

      - name: Run the container to test dbus
        run: |
          docker run -d --name dbus-test my-ubuntu-dbus:latest
          sleep 5  # Wait for dbus to start
          docker exec dbus-test bash -c "dbus-send --system --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.ListNames"

      - name: Cleanup
        run: docker rm -f dbus-test


  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run the dbus check
        run: |
          docker run --rm my-ubuntu-dbus:latest dbus-send --system --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.ListNames
